### ISSUE TITLE
java.lang.ClassNotFoundException: ExampleServerLauncher when running the example

### ISSUE THREAD

**Issue by theBadT** [eclipsesource/graphical-lsp#189]
I've just cloned the repo and followed the instructions provided in the README.
client -> yarn
server -> mvn clean install

Everything went fine so far. But still I'm not able to get the server up and running
1.) server/example/workflow-example - the folder does not contain any file named ExampleServerLauncher
2.) server\example\workflow-example\target\classes\com\eclipsesource\glsp\example\workflow - opening a CMD prompt and using java ExampleServerLauncher produces the exception.

Help would be highly appreciated. Might be a layer 8 problem, however.
Thanks

**Comment by planger** [comment]
Hi @theBadT, we typically start the GLSP server (class `ExampleServerLauncher`) from the IDE during development. In this case the IDE already takes care of the classpath settings based on the maven configuration (as specified in the pom files). For instance, if you import the all projects from the `server` directory as maven projects in Eclipse, the classpath will already be correct so that you can just create a new launch configuration for `ExampleServerLauncher` and run it.

If you don't want to use an IDE that takes care of that, you can also just launch the jar file that you've built with `mvn clean install`. Therefore, please use the following commands:
```shell
cd server
mvn clean install
cd server/example/workflow-example/target
java -jar workflow-example-0.2.0-SNAPSHOT-glsp.jar com.eclipsesource.glsp.example.workflow.ExampleServerLauncher
```

This should start the server and you should get the command output:
```
0 [main] INFO com.eclipsesource.glsp.server.ServerLauncher  - The graphical server launcher is ready to accept new client requests
```

Now you can continue with starting the client:
```shell
cd client
yarn
cd client/examples/workflow/browser-app
yarn start
```
and then open http://localhost:3000 in the browser

We should probably document that in the readme as well (ie. documenting how to start the example without IDE).

**Comment by theBadT** [comment]
works perfectly fine 😄 thanks for clarification
