### ISSUE TITLE
Implement SelectionService to track selected elements reliably

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipsesource/graphical-lsp#201]
Currently there is no easy way to determine the selected elements. In most cases, we use one of the following two approaches, depending on where we need this information. However, both approaches do not work in all cases:

- Iterate through the complete model and collect all elements that have the `selected` flag. This flag is currently set by the `SelectAction` and its corresponding command. 
Therefore, this approach can only be used when we can ensure that all commands that work on the selected flag have been processed as otherwise we may work on outdated information.

- Listening to selection changes based on mouse events and aggregating the information  (`SelectionTracker` class). This uses the `MoveMouseListener` from Sprotty which actually dispatches the `SelectAction` in order to get the selection information as soon as possible. This is necessary for most tools which need to act on the mouse-listener level themselves.
The main issue for using a mouse listener is that any other listeners/actions/commands that dispatch a `SelectAction` or the `DiagramKeybindingContribution` that selects all elements (ctrl+a) cannot be tracked. Furthermore, the tool listeners inherit from the `SelectionTracker` class but tools can be enabled and disabled at any time, so any selection that is present prior to the tools activation is lost as well.

What we need is a reliable way to track selection and make that information available as soon as possible. The selection service should track any action that manipulates the `selected` flag but also react to what information is sent from the server (if we allow the server to manipulate selection). Ideally, this information is available to the tools and the tools can react to selection changes accordingly.

**Comment by tortmayr** [comment]
I completly agree and after giving it some thought I believe we need to address several issues to be able to provide a reliable selection service.

First and foremost it must be possible to prioritize certain `MouseListeners` i.e. on mouse events the mouse listener for the `SelectionService` must be triggered before any mouse listener of selection aware `Tools`.

Second, the current approach for determining if an element is selected needs to be reconsidered.
At the moment the sprotty `SelectMouseListner' simply sets a `selected` flag of the SModelElement on click. Components that want to retrieve the current selection state have to iterate over the whole SModel and collect all elements with 'selected'=true.

Apart from potential performance issues, this introduces additional dependencies for selection aware tools. Theoretically the event handling of selection-dependent mouse listeners has to be deferred until the 'SelectMouseListener' has handled the event and the resulting 'SelectActions' (resp. SelectCommands) have been handled. Otherwise the newest select events might not be represented in the 'SModel'.

**Comment by tortmayr** [comment]
I propose the following solution

- Introduce a 'priority' property for the `MouseListener` class
- Extend the 'MouseTool' so that the registered listeners get sorted by priority before event delegation

- Introduce a singleton 'SelectionService' that maintains the currently selected element ids
- Extend the existing 'SelectMouseListener' so that the `currentSelection` of the selection service is also updated on change

Via higher priority it can be ensured that the new 'SelectMouseListener' is the first in line. Selection-aware listener can then use the  up-to-date 'SelectionService' and do not need to wait until the 'SelectActions' are dispatched and handled.
