### ISSUE TITLE
Support multi-select in dispatching SelectAction

### ISSUE THREAD

**Issue by planger** [eclipsesource/graphical-lsp#58]
Currently it seems we are only dispatching a `SelectAction` with the last selected element instead of including all selected elements.

**Comment by tortmayr** [comment]
That's because base sprotty sends one <code>SelectAction</code> for each individual element selection. The most import reason for this is to enable visual feedback during the selection process.

I propose the implementation of an <code>SelectionService</code> on client that caches all currently selected elements. This service can then send real multi-select actions to the diagram server.

In addition, this would also be beneficial for the performance of selection-aware tools. This tools can use the information provided by the <code>SelectionService</code> instead of iterating through the entire model to find selected elements.

**Comment by tortmayr** [comment]
This issue has been addressed with #201
